---
title: "Week  6 Assignment"
author: "David Russo"
date: "2/18/2017"
output:
  pdf_document: default
  html_document: default
---

* 4.7 #10
```{r set_up, echo = FALSE, include = FALSE}
# load libraries
library(tidyverse)
library(MASS)
library(ISLR)
library(class)
# load data
data(Weekly)
```

  + a.
```{r a_numeric_summaries, echo = FALSE}
count_results <- 
Weekly %>%
  group_by(Direction) %>%
    summarise(Count = n(),
              Percent = paste0(round(Count/nrow(Weekly), 2)*100, "%"))
knitr::kable(count_results)

mean_covariates <- 
Weekly %>%
  group_by(Direction) %>%
    summarise(`Mean Lag1` = round(mean(Lag1), 4),
              `Mean Lag2` = round(mean(Lag2), 4),
              `Mean Lag3` = round(mean(Lag3), 4),
              `Mean Lag4` = round(mean(Lag4), 4), 
              `Mean Lag5` = round(mean(Lag5), 4),
              `Mean Volume` = round(mean(Volume), 4),
              `Mean Today` = round(mean(Today), 4))
knitr::kable(mean_covariates)


knitr::kable(cor(Weekly[!names(Weekly) %in% "Direction"]))
```

```{r a_graphical_summaries, echo = FALSE}

```

