---
title: "Week 8 Assignment"
author: "David Russo"
date: "3/9/2017"
output: pdf_document
---

```{r overhead, echo = FALSE, include = FALSE}
library(tidyverse)
library(ISLR)
```

10.7 #3

  * a)
```{r a, echo = TRUE, include = TRUE}
obs <- data.frame(
  X1 = c(1, 1, 0, 5, 6, 4),
  X2 = c(4, 3, 4, 1, 2, 0)
)

obs %>%
  ggplot(aes(x = X1, y = X2)) +
  geom_point()

```

  * b)
```{r b, echo = TRUE, include = TRUE}
# set random number seed for replicable results
set.seed(2017)

# assign the labels
obs$cluster <- sample(rep(c(1, 2), each = 3), 6, replace = FALSE)

# print the labels
obs

# plot the labels
obs %>%
  dplyr::select(X1, X2, cluster) %>% 
  ggplot(aes(x = X1, y = X2, color = as.factor(cluster))) +
  geom_point()
```

  * c)
```{r c, echo = TRUE, include = TRUE}
centroids <-
  obs %>%
  dplyr::group_by(cluster) %>%
  dplyr::summarise(centroid_X1 = round(mean(X1), 2), centroid_X2 = round(mean(X2), 2)) %>%
  as.data.frame()

centroids
  
```

  * d)
```{r d, echo = TRUE, include = TRUE}

# create distance from cluster1 centroid
obs$dist_from_cluster1_centroid <- round(
  sqrt((obs$X1 - centroids$centroid_X1[centroids$cluster == 1])^2 + 
       (obs$X2 - centroids$centroid_X2[centroids$cluster == 1])^2), 4)

# create distance from cluster2 centroid
obs$dist_from_cluster2_centroid <- round(
  sqrt((obs$X1 - centroids$centroid_X1[centroids$cluster == 2])^2 + 
       (obs$X2 - centroids$centroid_X2[centroids$cluster == 2])^2), 4)

obs$new_cluster <-
  ifelse(obs$dist_from_cluster1_centroid <= obs$dist_from_cluster2_centroid, 1, 2)

obs

```

  * e)
```{r e, echo = TRUE, include = TRUE}

cluster_difference <- FALSE

while(cluster_difference == FALSE){

# reset obs$cluster to obs$new_cluster
obs$cluster <- obs$new_cluster
  
# create distance from cluster1 centroid
obs$dist_from_cluster1_centroid <- round(
  sqrt((obs$X1 - centroids$centroid_X1[centroids$cluster == 1])^2 + 
       (obs$X2 - centroids$centroid_X2[centroids$cluster == 1])^2), 4)

# create distance from cluster2 centroid
obs$dist_from_cluster2_centroid <- round(
  sqrt((obs$X1 - centroids$centroid_X1[centroids$cluster == 2])^2 + 
       (obs$X2 - centroids$centroid_X2[centroids$cluster == 2])^2), 4)

obs$new_cluster <-
  ifelse(obs$dist_from_cluster1_centroid <= obs$dist_from_cluster2_centroid, 1, 2)

cluster_difference <- all(obs$cluster == obs$new_cluster)

print(obs)

}

```

The clustering only took one iteration until the algorithm converged.

  * f)
```{r f, echo = TRUE, include = TRUE}
obs %>%
  dplyr::select(X1, X2, new_cluster) %>% 
  ggplot(aes(x = X1, y = X2, color = as.factor(new_cluster))) +
  geom_point()
```

10.7 #7
```{r demonstration, echo = TRUE, include = TRUE}
# load the data
data("USArrests")

# scale the data so that each variable has a mean of 0 and a variance of 1
usa_scaled <- scale(USArrests)
# verify that the scaled data's variables all have mean 0 and variance 1
apply(usa_scaled, 2, function(x) round(c(mean(x), var(x)), 2))

# create data frame of combinations of rows of usa_scaled data set
# there are choose(50, 2) = 1225 ways to choose 2 observations out of 50
combs <- t(combn(50, 2))
head(combs)

```





